/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * TrinityKitWP API
 * API para criar posts e fazer upload de imagens no WordPress
 * OpenAPI spec version: 1.0.0
 */
import type { GetAssets200Data } from './getAssets200Data';

export type GetAssets200 = {
  success?: boolean;
  data?: GetAssets200Data;
};
