/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * TrinityKitWP API
 * API para criar posts e fazer upload de imagens no WordPress
 * OpenAPI spec version: 1.0.0
 */
import type { GetAssets401Data } from './getAssets401Data';

export type GetAssets401 = {
  code?: string;
  message?: string;
  data?: GetAssets401Data;
};
