/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * TrinityKitWP API
 * API para criar posts e fazer upload de imagens no WordPress
 * OpenAPI spec version: 1.0.0
 */

export type GetAssets200Data = {
  /** URL do PDF da apresentação da empresa */
  company_presentation?: string;
  /** URL do PDF do catálogo de Plásticos & Elastômeros */
  plastics_catalog?: string;
  /** URL do PDF do catálogo de Borrachas */
  rubber_catalog?: string;
  /** URL do PDF do catálogo de Adesivos */
  adhesives_catalog?: string;
};
